### PR TITLE
Add EMTB Profile

### PR DESCRIPTION
**Pull request by droogmic**
A proposal,
changed lines are 222 to 230.

### CODE REVIEW

**Comment by zossebart** [comment]
Thanks for your proposal. I will review your pr as soon as I'm back from vacation in a week.

**Comment by zossebart** [comment]
@droogmic As I do not own an e-mtb, could you please shortly describe the intention of your emtb-variant? It seems the main change is the raised mtb_sac_penalty (also for low values like mtb:scale=1). Is it more difficult to ride them with an e-mtb?

**Comment by droogmic** [comment]
Hi @zossebart ,
In hindsight I think I was too hasty with my changeset, so I will rework it. But I still need your advice.
The obvious difference between an emtb and an mtb would be that going uphill is easier, but I have yet to see where to modify this.
The less obvious way of seeing an emtb is a very heavy mtb, so doing challenging terrain (mtb:scale > 1) is less fun...

The changes I made do mtb_sac_penalty are also due to my local area being very steep. There are hiking paths a sac_scale=T2 which are practically impassible with an emtb, and require carrying even a normal mtb. I would not expect a router to ever choose these unless totally necessary.
I wonder if this might be different to where you ride.

**Comment by zossebart** [comment]
Hi @droogmic 

> Hi @zossebart ,
> In hindsight I think I was too hasty with my changeset, so I will rework it. But I still need your advice.
> The obvious difference between an emtb and an mtb would be that going uphill is easier, but I have yet to see where to modify this.

Uphill routing can be modified with the following parts of the profile:

- uphillcost: cost added according to the elevation data for all ways (regardless of osm tags). You might reduce this for emtb

- consideruphill: this is a switch which enables/disables special handling of uphill passages. If enabled (default in my profiles), it adds uh_penalty for paths that go uphill (according to elevation data).
It also adds uh_difficult_penalty for ways which have an inclination tag indicating that the way goes uphill (regardless of the elevation data). I just discovered that I might have to overthink this again, maybe this is only an artefact left from older versions of the profile. However, for emtb, you might experiment with setting consideruphill to false.

- mtb_uh_penalty: this is added for all ways that have an inclination tag indicating that the way goes uphill and mtb:scale:uphill tags or mtb:scale=6


> The less obvious way of seeing an emtb is a very heavy mtb, so doing challenging terrain (mtb:scale > 1) is less fun...

I guess you refer to downhill passages here? Then rising mtb_sac_penalty should be the right way to go.

> 
> The changes I made do mtb_sac_penalty are also due to my local area being very steep. There are hiking paths a sac_scale=T2 which are practically impassible with an emtb, and require carrying even a normal mtb. I would not expect a router to ever choose these unless totally necessary.

Normally, the steepness of a way should be reflected in the mtb:scale rating. However, it seems the ways you are referring to do not have mtb:scale tags, but only sac_scale tags set. As I understand it, sac_scale does not take steepness into account. So using sac_scale when no mtb_scale is available might not be ideal after all...maybe I have to rethink this.
Another way to influence the routing regarding downhill steepness would be to increase downhillcost.

> I wonder if this might be different to where you ride.
Yes. There's not very much steep terrain around here.

In general, I would appreciate it to seperate your emtb changes into a distinct profile, as you did in your first commit.

**Comment by droogmic** [comment]
> it seems the ways you are referring to do not have mtb:scale tags, but only sac_scale tags set.

Indeed, e.g. there is a T2 without mtb:scale which would be equivalent to a mtb:scale:uphill=4/5 which I want to avoid being routed to.

> I guess you refer to downhill passages here? Then rising mtb_sac_penalty should be the right way to go.

Both uphill and downhill? the main exception is mtb:scale:uphill=<2 is easier on emtb, let me see what I can do about that...

I need to reread the logic, but I think I want to somehow get a stronger downhill penalty, a reduced penalty for slight uphill, and a stronger penalty for steep uphill.

> In general, I would appreciate it to seperate your emtb changes into a distinct profile, as you did in your first commit.

Interesting, I would prefer to just propose alternative parameters to a standard mtb profile, but that might be feasible.
I will make a duplicate as requested, but leave it as a diff while I am still proposing changes :)

**Comment by zossebart** [comment]
> > it seems the ways you are referring to do not have mtb:scale tags, but only sac_scale tags set.
> 
> Indeed, e.g. there is a T2 without mtb:scale which would be equivalent to a mtb:scale:uphill=4/5 which I want to avoid being routed to.

Would you say that it can be generally said that T2 is roughly equivalent to mtb:scale:uphill=4/5 or only in this special case? 
I assume you edit osm accordingly when you discover such a way? This way, it wouldn't be routed next time and others also benefit from it.

> 
> > I guess you refer to downhill passages here? Then rising mtb_sac_penalty should be the right way to go.
> 
> Both uphill and downhill? the main exception is mtb:scale:uphill=<2 is easier on emtb, let me see what I can do about that...
> 
> I need to reread the logic, but I think I want to somehow get a stronger downhill penalty, a reduced penalty for slight uphill, and a stronger penalty for steep uphill.

This should only be possible in a limited way. The uphillcost rises proportionally to the height-meters. You could play with the uphillcutoff, which gives the slope (percent) below which a way is not considered as uphill (and thus no uphillcost will be added).

> 
> > In general, I would appreciate it to seperate your emtb changes into a distinct profile, as you did in your first commit.
> 
> Interesting, I would prefer to just propose alternative parameters to a standard mtb profile, but that might be feasible.

I would also prefer it in this way (maybe with an e-mtb profile parameter to switch the behaviour), but I'm a LocusMaps user and the developer decided to limit the supported profile parameters to the most commonly used ones (avoid ferries, wet conditions etc.). So maybe create it with parameter(s) for the standard profile and then just create a copy with the parameters pre-set for e-mtb (for use with Locus)?

With more profile variants, this gets laborious though. Poutnik solves this with a profile template and a script that creates the different variants from this template, but this is not very end-user friendly I think...

**Comment by droogmic** [comment]
Declining for now...

**Pull request closed without merging**
